weights: yolov5n.pt
cfg: ./models_v5.0/yolov5n.yaml
data: /home/syauqinadhif/yolov5/yolov5-train/data/goalpost.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 64
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: yolov5-deepsparse
name: yolov5n-goalpost
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
recipe: ../recipes/yolov5.transfer_learn_pruned_quantized.md
disable_ema: false
max_train_steps: -1
max_eval_steps: -1
one_shot: false
num_export_samples: 0
save_dir: yolov5-deepsparse/yolov5n-goalpost8
